// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "test.h"

namespace utils
{
int x; 
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
end();
}

}

//namespace utils
/*
int x; 

*/

#if 1

#endif
Dad::Dad(int X, int Y, int W, int H, const char *L)
  : Fl_Window(X, Y, W, H, L) {
  _Dad();
}

Dad::Dad(int W, int H, const char *L)
  : Fl_Window(0, 0, W, H, L) {
  clear_flag(16);
  _Dad();
}

Dad::Dad()
  : Fl_Window(0, 0, 108, 100, 0) {
  clear_flag(16);
  _Dad();
}

void Dad::_Dad() {
this->box(FL_FLAT_BOX);
this->color(FL_BACKGROUND_COLOR);
this->selection_color(FL_BACKGROUND_COLOR);
this->labeltype(FL_NO_LABEL);
this->labelfont(0);
this->labelsize(14);
this->labelcolor(FL_FOREGROUND_COLOR);
this->align(Fl_Align(FL_ALIGN_TOP));
this->when(FL_WHEN_RELEASE);
{ gui.in = new Fl_Input(25, 25, 15, 24, "input:");
} // Fl_Input* in
{ gui.but = new Fl_Button(25, 25, 64, 20, "button");
} // Fl_Button* but
{ gui.age = new Fl_Input(25, 25, 15, 24, "input:");
  gui.age->tooltip("adsdad");
} // Fl_Input* age
end();
}

void Dad::init() {
  printf("Hello, World!\n");
}
