// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>

namespace utils
{
extern int x; 

class UserInterface : public Fl_Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
};

}

//namespace utils
/*
extern int x; 

*/

#if 1

#endif
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class Dad : public Fl_Window {
  void _Dad();
public:
  Dad(int X, int Y, int W, int H, const char *L = 0);
  Dad(int W, int H, const char *L = 0);
  Dad();
  struct gui {
  Fl_Input *in;
  Fl_Button *but;
  Fl_Input *age;
  int x; 

class innerClass {
};
  } gui;
  void init();
};
#endif
