#define TK_SEMI                             1
#define TK_INTEGER                          2
#define TK_FLOAT                            3
#define TK_STRING                           4
#define TK_TRUE                             5
#define TK_FALSE                            6
#define TK_NULL                             7
#define TK_QM                               8
#define TK_OR                               9
#define TK_AND                             10
#define TK_BITOR                           11
#define TK_BITXOR                          12
#define TK_BITAND                          13
#define TK_ILIKEOP                         14
#define TK_LIKEOP                          15
#define TK_NE                              16
#define TK_EQEQ                            17
#define TK_EQ3                             18
#define TK_NE3                             19
#define TK_WITHIN                          20
#define TK_IN                              21
#define TK_GT                              22
#define TK_LE                              23
#define TK_LT                              24
#define TK_GE                              25
#define TK_LSHIFT                          26
#define TK_RSHIFT                          27
#define TK_URSHIFT                         28
#define TK_PLUS                            29
#define TK_MINUS                           30
#define TK_STAR                            31
#define TK_SLASH                           32
#define TK_REM                             33
#define TK_BITNOT                          34
#define TK_BANG                            35
#define TK_COLLATE                         36
#define TK_ID                              37
#define TK_DOT                             38
#define TK_LB                              39
#define TK_RB                              40
#define TK_LC                              41
#define TK_RC                              42
#define TK_COLON                           43
#define TK_COMMA                           44
#define TK_LP                              45
#define TK_RP                              46
#define TK_UNION                           47
#define TK_EXCEPT                          48
#define TK_INTERSECT                       49
#define TK_ALL                             50
#define TK_SELECT                          51
#define TK_DISTINCT                        52
#define TK_AS                              53
#define TK_FROM                            54
#define TK_FLATTENOP                       55
#define TK_GROUP                           56
#define TK_BY                              57
#define TK_HAVING                          58
#define TK_ORDER                           59
#define TK_ASCENDING                       60
#define TK_DESCENDING                      61
#define TK_LIMIT                           62
#define TK_OFFSET                          63
#define TK_WHERE                           64
#define TK_BEGIN                           65
#define TK_ROLLBACK                        66
#define TK_COMMIT                          67
#define TK_CREATE                          68
#define TK_COLLECTION                      69
#define TK_IF                              70
#define TK_NOT                             71
#define TK_EXISTS                          72
#define TK_DROP                            73
#define TK_DELETE                          74
#define TK_UPDATE                          75
#define TK_SET                             76
#define TK_EQ                              77
#define TK_ELSE                            78
#define TK_INSERT                          79
#define TK_INTO                            80
#define TK_VALUE                           81
#define TK_ASYNC                           82
#define TK_SYNC                            83
#define TK_PRAGMA                          84
