#!/bin/sh
#squilu squilufreeze.nut /home/mingo/bin/squilu sqlite3-cc2.nut sqlite3-cc
SRC_SCRIPT=$1
squilu unify-code.nut ${SRC_SCRIPT}.nut ${SRC_SCRIPT}-unified.nut
squilu squilufreeze.nut /home/mingo/bin/squilu ${SRC_SCRIPT}-unified.nut ${SRC_SCRIPT}
chmod +x ${SRC_SCRIPT}

